new: dev: Update systemd-coredump to change groups
Added a patch to systemd-coredump in order to change the group of the core dump
files.  This is required for the cli commands show core-dump and copy core-dump,
since they run in netop mode.   This  feature is added as configurable option
using the config CoreDump.GroupName

Change-Id: I377da8530de3ac4e2399580b2823de05de159ecc
Signed-off-by: Satya Naik <satya.pra.naik@hpe.com>

diff --git a/yocto/openswitch/meta-distro-openswitch/recipes-ops/utils/ops-kdump/kdump b/yocto/openswitch/meta-distro-openswitch/recipes-ops/utils/ops-kdump/kdump
--- a/yocto/openswitch/meta-distro-openswitch/recipes-ops/utils/ops-kdump/kdump
+++ b/yocto/openswitch/meta-distro-openswitch/recipes-ops/utils/ops-kdump/kdump
@@ -39,7 +39,7 @@ KDUMP_INITRD=""
 function check_core_compress()
 {
     local files="/etc/os-release  /var/log/messages";
-
+    local vmcore_file_tar=""
     local time_stamp_fmt=$(date +"%Y%m%d.%H%M%S")
 
     local kdump_path=`grep ^path $KDUMP_CONFIG_FILE | cut -d' '  -f2-`
@@ -67,8 +67,26 @@ function check_core_compress()
         tar -czf ${coredir}/vmcore_incomplete.tar.gz ${coredir}/vmcore ${files}
         if [ $? -eq 0 ]; then
             rm -f ${coredir}/vmcore  ${coredir}/vmcore-dmesg.txt
-            mv ${coredir}/vmcore_incomplete.tar.gz ${coredir}/vmcore.${time_stamp_fmt}.tar.gz
-            $LOGGER "archived and compressed vmcore to ${coredir}"
+
+            #Compressed core file name
+            vmcore_file_tar="${coredir}/vmcore.${time_stamp_fmt}.tar.gz"
+
+            mv ${coredir}/vmcore_incomplete.tar.gz ${vmcore_file_tar}
+            if [[ $? -eq 0 ]]; then
+                $LOGGER "archived and compressed vmcore to ${coredir}"
+
+                # Kernel vmcore is generated by root user. netop user can't read
+                # this vmcore file. We created group "ops_coredump" and changed
+                # ownership to it . netop user use tftp/sftp client to copy
+                # corefile from switch to external server.
+
+                chown root:ops_coredump  ${vmcore_file_tar}
+                if [[ $? -ne 0 ]]; then
+                    $LOGGER "failed to change ownership to ops_coredump group"
+                fi
+            else
+                $LOGGER "failed to archive and compress vmcore"
+            fi
         else
             $LOGGER "failed to compress vmcore to $coredir"
         fi
